image: "rustlang/rust:nightly"

build-linux:
  script:
    - make build-linux
  artifacts:
    paths:
      - target/release/envkit

build-osx:
  script:
    - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
    - apt-get install software-properties-common python-software-properties
    - apt-get update
    - apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-6.0 main"
    - apt-get install -y clang-6.0 lld-6.0
    - make build-osx
  cache:
    key: osxcross
    paths:
      - osxcross
  artifacts:
    paths:
      - target/x86_64-apple-darwin/release/envkit

test:
  script:
    - cargo test
