image: "rustlang/rust:nightly"

build-linux:
  script:
    - make build-linux
  artifacts:
    paths:
      - target/release/envkit

build-osx:
  script:
    - apt install clang gcc g++
    - make build-osx
  cache:
    key: osxcross
    paths:
      - osxcross
  artifacts:
    paths:
      - target/x86_64-apple-darwin/release/envkit

test:
  script:
    - cargo test
