image: "rustlang/rust:nightly"

stages:
  - test
  - build

build-linux:
  stage: build
  script:
    - make build-linux
  artifacts:
    name: "envkit-linux-$CI_COMMIT_TAG"
    paths:
      - target/release/envkit
  only:
    - tags

build-osx:
  stage: build
  script:
    - apt-get update
    - apt-get install -y clang cmake
    - make build-osx
  artifacts:
    name: "envkit-osx-$CI_COMMIT_TAG"
    paths:
      - target/x86_64-apple-darwin/release/envkit
  only:
    - tags

test:
  stage: test
  script:
    - cargo test
