image: "rustlang/rust:nightly"

stages:
  - build
  - test

# Build

build-linux:
  stage: build
  script:
    - make build-linux
  artifacts:
    paths:
      - target/release/envkit

build-osx:
  stage: build
  script:
    - apt install clang gcc g++ zlib1g-dev libmpc-dev libmpfr-dev libgmp-dev
    - make build-osx
  cache:
    key: osxcross
    paths:
      - osxcross
  artifacts:
    paths:
      - target/x86_64-apple-darwin/release/envkit

# Test

test:
  stage: test
  script:
    - cargo test
