image: "rustlang/rust:nightly"

build-linux:
  script:
    - make build-linux
  artifacts:
    paths:
      - target/release/envkit
  only:
    - tags

build-osx:
  script:
    - apt-get update
    - apt-get install -y clang cmake
    - make build-osx
  cache:
    key: osxcross
    paths:
      - osxcross
  artifacts:
    paths:
      - target/x86_64-apple-darwin/release/envkit

test:
  script:
    - cargo test
  only:
    - tags
