image: "rustlang/rust:nightly"

build-linux:
  script:
    - make build-linux
  artifacts:
    name: "envkit-linux-$CI_COMMIT_TAG"
    paths:
      - target/release/envkit
  only:
    - tags

build-osx:
  script:
    - apt-get update
    - apt-get install -y clang cmake
    - make build-osx
  cache:
    key: osxcross
    paths:
      - osxcross/target/bin
  artifacts:
    name: "envkit-osx-$CI_COMMIT_TAG"
    paths:
      - target/x86_64-apple-darwin/release/envkit
  only:
    - tags

test:
  script:
    - cargo test
