[package]
name = "envkit"
version = "0.2.0"
authors = ["Viktor Kuroljov <viktor@ku.family>"]
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
clap = { version = "4.3.3", features = ["derive"] }

[dev-dependencies]
trycmd = "0.14.16"
